use dioxus::prelude::*;
use dioxus_free_icons::Icon;
use dioxus_free_icons::icons::fa_brands_icons::FaGithub;
use pulldown_cmark::{Options, Parser, html};

// Generated by fancier/scripts/generate-oss-notices.sh (which shells out to
// `cargo about`) from the ACTUAL, current Cargo dependency graph -- not a
// hand-maintained list, so this page can't drift stale the way
// THIRD_PARTY_NOTICES.md's hand-written Lucide section could have. Release
// builds regenerate both files (fancier/scripts/build-release.sh); the
// checked-in snapshot here is what makes `cargo check`/`dx serve` work
// without cargo-about installed. See fancier/about.toml (repo root
// about.toml, shared with dovecote) for the accepted-license policy.
const FANCIER_OSS_MD: &str = include_str!("../../generated/oss-licenses.md");
const DOVECOTE_OSS_MD: &str = include_str!("../../../dovecote/generated/oss-licenses.md");

// Scoped to #oss-md, same convention as #api-md in api_reference.rs: colors
// reference the DaisyUI --color-* custom properties directly so this
// tracks the app's light/dark theme toggle. <details>/<summary> is how the
// generated inventory keeps hundreds of packages' worth of license text off
// the rendered page by default (collapsed until clicked) -- the layout
// never "blows up" because nothing long renders open. `pre` still gets
// horizontal-only overflow handling for the rare license text with an
// unusually long line.
const MARKDOWN_STYLE: &str = r#"<style>
  #oss-md { color: var(--color-base-content); line-height: 1.7; }
  #oss-md h3 { font-size: 1.2rem; font-weight: 700; margin: 1.75rem 0 .75rem; color: var(--color-secondary); }
  #oss-md p { margin: 1rem 0; }
  #oss-md a { color: var(--color-secondary); text-decoration: underline; text-underline-offset: 2px; }
  #oss-md ul { margin: 1rem 0 1rem 1.5rem; list-style: disc; }
  #oss-md li { margin: .35rem 0; }
  #oss-md details { margin: .5rem 0 1.5rem; border: 1px solid var(--color-base-300); border-radius: .5rem; padding: .5rem .75rem; }
  #oss-md summary { cursor: pointer; font-weight: 600; padding: .25rem 0; }
  #oss-md pre { background: var(--color-base-300); color: var(--color-base-content); padding: 1rem 1.25rem; border-radius: .75rem; overflow-x: auto; margin: 1rem 0; }
  #oss-md pre code { background: transparent; padding: 0; font-size: .8em; white-space: pre; }
  #oss-md strong { font-weight: 700; }
</style>"#;

fn render_markdown(src: &str) -> String {
  let mut options = Options::empty();
  options.insert(Options::ENABLE_STRIKETHROUGH);
  let parser = Parser::new_ext(src, options);
  let mut body = String::new();
  html::push_html(&mut body, parser);
  body
}

#[component]
pub fn OpenSourcePage() -> Element {
  let fancier_html = use_memo(|| render_markdown(FANCIER_OSS_MD));
  let dovecote_html = use_memo(|| render_markdown(DOVECOTE_OSS_MD));

  rsx! {
    section { class: "py-16 md:py-24",
      div { class: "max-w-4xl mx-auto px-4 md:px-8",
        h1 { class: "text-4xl md:text-5xl font-extrabold tracking-tighter mb-3", "Open Source" }
        p { class: "text-lg text-base-content/70 leading-relaxed mb-4",
          "PidgeIoT is built on the work of a lot of other people. This page attributes all of it: the platform's own license, the pieces you see and interact with directly, and the full, "
          strong { "auto-generated" }
          " inventory of every Rust crate compiled into what actually ships to your browser and to the edge."
        }

        // (a) PidgeIoT's own licensing
        div { class: "mt-12 text-base-content/70 leading-relaxed",
          h2 { class: "text-2xl md:text-3xl font-bold mb-4 tracking-tight text-base-content",
            "PidgeIoT itself"
          }
          p { class: "mb-4",
            "PidgeIoT is licensed under the GNU Affero General Public License v3.0 (AGPL-3.0). It's developed in the open -- the full source for the edge backend, the dashboard you're using right now, and the device-side firmware libraries all live on GitHub."
          }
          a {
            class: "link link-secondary inline-flex items-center gap-2",
            href: "https://github.com/justins-engineering/pidgeiot",
            target: "_blank",
            rel: "noopener",
            Icon { icon: FaGithub, class: "size-4", title: "GitHub" }
            "github.com/justins-engineering/pidgeiot"
          }
        }

        // (b) Named credits for the direct, user-visible pieces
        div { class: "mt-12 text-base-content/70 leading-relaxed",
          h2 { class: "text-2xl md:text-3xl font-bold mb-4 tracking-tight text-base-content",
            "Named credits"
          }
          p { class: "mb-4",
            "The pieces that most directly shape what you see and use:"
          }
          ul { class: "list-disc ml-6 space-y-3",
            li {
              a { class: "link link-secondary", href: "https://lucide.dev", target: "_blank", rel: "noopener", "Lucide" }
              " (ISC, with Feather-derived portions under MIT) -- every inline icon in this app, including the bird mark standing in as the logo. Full notices in "
              a { class: "link link-secondary", href: "https://github.com/justins-engineering/pidgeiot/blob/main/THIRD_PARTY_NOTICES.md", target: "_blank", rel: "noopener", "THIRD_PARTY_NOTICES.md" }
              "."
            }
            li {
              a { class: "link link-secondary", href: "https://daisyui.com", target: "_blank", rel: "noopener", "daisyUI" }
              " (MIT) -- the component/theme layer this app's design is built on."
            }
            li {
              a { class: "link link-secondary", href: "https://tailwindcss.com", target: "_blank", rel: "noopener", "Tailwind CSS" }
              " (MIT) -- the utility CSS framework daisyUI sits on and every page's styling is written in."
            }
            li {
              a { class: "link link-secondary", href: "https://dioxuslabs.com", target: "_blank", rel: "noopener", "Dioxus" }
              " (MIT/Apache-2.0) -- the Rust UI framework this entire dashboard is built with."
            }
            li {
              a { class: "link link-secondary", href: "https://www.ory.sh/kratos", target: "_blank", rel: "noopener", "Ory Kratos" }
              " (Apache-2.0) -- the self-hosted identity system behind dashboard accounts, login, and password recovery."
            }
          }
        }

        // (c) Full generated crate inventory
        div { class: "mt-12 text-base-content/70 leading-relaxed",
          h2 { class: "text-2xl md:text-3xl font-bold mb-4 tracking-tight text-base-content",
            "Every crate, generated from the actual build"
          }
          p { class: "mb-2",
            "Every Rust crate compiled into what ships, grouped by license, generated directly from the real dependency graph with "
            a { class: "link link-secondary", href: "https://github.com/EmbarkStudios/cargo-about", target: "_blank", rel: "noopener", "cargo-about" }
            " -- not hand-maintained, so it can't go stale. Each license's text is collapsed by default; click a heading to expand it."
          }

          // A single #oss-md scope wraps both subsections so the shared
          // stylesheet only needs injecting once; dangerous_inner_html
          // replaces all of an element's children, so it can't be mixed
          // with sibling rsx nodes on the same element -- the style tag
          // and each rendered body each get their own child div instead.
          div { id: "oss-md",
            div { dangerous_inner_html: "{MARKDOWN_STYLE}" }
            h3 { class: "text-xl font-bold mt-8 mb-2 text-base-content", "fancier (this dashboard)" }
            div { dangerous_inner_html: "{fancier_html}" }
            h3 { class: "text-xl font-bold mt-10 mb-2 text-base-content", "dovecote (the edge backend)" }
            div { dangerous_inner_html: "{dovecote_html}" }
          }
        }
      }
    }
  }
}
