[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = ["-Cllvm-args=--inline-threshold=300", "--cfg=uuid_unstable"]

[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1
strip = "debuginfo"
incremental = false

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[package.metadata.release]
release = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-bulk-memory"]
