name = "dovecote"
compatibility_date = "2026-06-05"
send_metrics = false
main = "build/worker/shim.mjs"

[[routes]]
pattern = "api.pidgeiot.com"
custom_domain = true
zone_name = "pidgeiot.com"

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 0

[vars]
KRATOS_BROWSER_URL = "https://auth.pidgeiot.com"
ROOT_URL = "https://pidgeiot.com"

[[hyperdrive]]
binding = "YugabyteDB"
id = "f2c59dfa75114889815fd453ac0db62a"

[durable_objects]
bindings = [{ name = "PIGEONS", class_name = "Pigeons" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Pigeons"]

[build]
command = "cargo install -q worker-build && worker-build --release"
watch_dir = ["./src"]

[env.dev.vars]
KRATOS_BROWSER_URL = "http://127.0.0.1:4433"
ROOT_URL = "http://127.0.0.1:4433"

[env.dev.durable_objects]
# the `class_name` uses the Rust struct identifier name
bindings = [{ name = "PIGEONS", class_name = "Pigeons" }]

[[env.dev.hyperdrive]]
binding = "YugabyteDB"
id = ""
localConnectionString = "postgres://kratos:secret@127.0.0.1:5432/dovecote?sslmode=disable"
